# Generated by Django 3.2.2 on 2021-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skillImage/')),
                ('title', models.CharField(max_length=50)),
                ('descipt', models.TextField(blank=True, max_length=500)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
