# Generated by Django 3.2.2 on 2021-05-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=50)),
                ('cEmail', models.CharField(max_length=50)),
                ('cComment', models.TextField(max_length=1000)),
            ],
        ),
    ]
